module.exports = [
  'What is the worst possible name for a luxury perfume?',
  'What would your autobiography be called if it were brutally honest?',
  'What is a terrible thing to hear from your dentist?',
  'What is the least impressive superpower?',
  'What should never be a pizza topping, but probably already is?',
  'What would your pet complain about in a review of you?',
  'What is the worst thing to accidentally say on a first date?',
  'What is a suspiciously specific rule at your imaginary hotel?',
  'What is the worst slogan for a gym?',
  'What would a ghost do to mildly inconvenience you?',
  'What is the least intimidating pirate name?',
  'What is a ridiculous excuse for being three hours late?',
  'What would aliens assume is our most important human tradition?',
  'What is a terrible prize to win on a game show?',
  'What should be an Olympic sport, but definitely is not?',
  'What would you name a restaurant that only serves leftovers?',
  'What is the worst advice a fortune cookie could give?',
  'What is the most embarrassing thing for a robot to malfunction doing?',
  'What would your fridge say if it could talk?',
  'What is the worst theme for a wedding?',
  'What is an unnecessary feature for a smart toaster?',
  'What is the title of the least exciting action movie?',
  'What is a terrible password that somehow describes your personality?',
  'What would be a terrible thing to find in a time capsule?',
  'What is the weirdest thing to put on a résumé?',
  'What is the worst possible mascot for a hospital?',
  'What is the official motto of Procrastination Island?',
  'What is the most useless app you could invent?',
  'What is an awful name for a cruise ship?',
  'What would a villain do if their budget were only five dollars?',
  'What would you put on a warning label attached to yourself?',
  'What is a strange hill you would absolutely die on?',
  'What is a terrible item to bring to a potluck?',
  'What is the worst thing a GPS could say mid-journey?',
  'What is the least convincing disguise imaginable?',
  'What would your browser tabs call their group chat?'
];
